### Dashboard Route
GET http://localhost:3000/

### Not Found
GET http://localhost:3000/api/

### Get all Users Route
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc
### Authorization: Bearer {token}

### Get single User Route
GET http://localhost:3000/api/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc
### Authorization: Bearer {token}

### Register User Route
POST http://localhost:3000/api/register/
Content-Type: application/json 

{
    "firstname": "Emmanuel",
    "lastname": "Dominic",
    "email": "ematembu2@gmail.com",
    "password": "Password123"
}

### Register User 2 Route
POST http://localhost:3000/api/register/
Content-Type: application/json 

{
    "firstname": "Matembu",
    "lastname": "Emmanuel",
    "email": "ematembu@gmail.com",
    "password": "Password123"
}

### Login User Route
POST http://localhost:3000/api/login/
Content-Type: application/json

{
    "email": "ematembu2@gmail.com",
    "password": "Password123"
}

### Delete User Route
DELETE http://localhost:3000/api/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc
### Authorization: Bearer {token}

### Update User Route
PATCH http://localhost:3000/api/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

{
    "firstname": "Michael",
    "lastname": "Thomas",
    "password": "Password123"
}

### Get all products Route
GET http://localhost:3000/api/products/

### Create product Route
POST http://localhost:3000/api/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

{
    "name": "Mac Book",
    "price": "2000"
}

### Get single product Route
GET http://localhost:3000/api/products/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Update product Route
PATCH http://localhost:3000/api/products/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

{
    "name": "Macbook",
    "price": "1900"
}

### Delete product Route
DELETE http://localhost:3000/api/products/11/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Get all orders by given user Route
GET http://localhost:3000/api/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Create order Route
POST http://localhost:3000/api/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Get single order Route
GET http://localhost:3000/api/orders/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Update order Route
PATCH http://localhost:3000/api/orders/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

{
    "status": "closed"
}

### Add products to an order Route
POST http://localhost:3000/api/orders/1/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

{
    "productId": "1",
    "quantity": "2"
}

### Most 5 popular products Route
GET http://localhost:3000/api/dashboard/popular/

### Completed Orders Route
GET http://localhost:3000/api/dashboard/completed/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiRW1tYW51ZWwiLCJsYXN0bmFtZSI6IkRvbWluaWMiLCJlbWFpbCI6ImVtYXRlbWJ1MkBnbWFpbC5jb20iLCJpYXQiOjE2Nzc5NDk4MTN9.ygBxAYTtVRsNfTyZP3rA3n-hL-BHMqh6b-e1R6SyLwc

### Get all Orders Route
GET http://localhost:3000/api/dashboard/orders/1/
